// Generated by gencpp from file chess/Player.msg
// DO NOT EDIT!


#ifndef CHESS_MESSAGE_PLAYER_H
#define CHESS_MESSAGE_PLAYER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chess
{
template <class ContainerAllocator>
struct Player_
{
  typedef Player_<ContainerAllocator> Type;

  Player_()
    : id(0)  {
    }
  Player_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(WHITE)
  #undef WHITE
#endif
#if defined(_WIN32) && defined(BLACK)
  #undef BLACK
#endif

  enum {
    WHITE = 0u,
    BLACK = 1u,
  };


  typedef boost::shared_ptr< ::chess::Player_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chess::Player_<ContainerAllocator> const> ConstPtr;

}; // struct Player_

typedef ::chess::Player_<std::allocator<void> > Player;

typedef boost::shared_ptr< ::chess::Player > PlayerPtr;
typedef boost::shared_ptr< ::chess::Player const> PlayerConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chess::Player_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chess::Player_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chess::Player_<ContainerAllocator1> & lhs, const ::chess::Player_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chess::Player_<ContainerAllocator1> & lhs, const ::chess::Player_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chess

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::chess::Player_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess::Player_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess::Player_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess::Player_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess::Player_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess::Player_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chess::Player_<ContainerAllocator> >
{
  static const char* value()
  {
    return "702ce2a9d992b93a9f0e4effdd691b99";
  }

  static const char* value(const ::chess::Player_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x702ce2a9d992b93aULL;
  static const uint64_t static_value2 = 0x9f0e4effdd691b99ULL;
};

template<class ContainerAllocator>
struct DataType< ::chess::Player_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chess/Player";
  }

  static const char* value(const ::chess::Player_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chess::Player_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 WHITE=0\n"
"uint8 BLACK=1\n"
"\n"
"uint8 id  # one of the two options above\n"
;
  }

  static const char* value(const ::chess::Player_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chess::Player_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Player_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chess::Player_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chess::Player_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHESS_MESSAGE_PLAYER_H
