# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from chess/Chessboard.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import chess.msg

class Chessboard(genpy.Message):
  _md5sum = "f9b8a96936f1ecbd729fc4d2fa9fe3ce"
  _type = "chess/Chessboard"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """chess/Chesspiece[64] squares

================================================================================
MSG: chess/Chesspiece
string KING=k
string QUEEN=q
string ROOK=r
string KNIGHT=n
string BISHOP=b
string PAWN=p
string EMPTY=

chess/Player player
string kind

================================================================================
MSG: chess/Player
uint8 WHITE=0
uint8 BLACK=1

uint8 id  # one of the two options above
"""
  __slots__ = ['squares']
  _slot_types = ['chess/Chesspiece[64]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       squares

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Chessboard, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.squares is None:
        self.squares = [chess.msg.Chesspiece() for _ in range(64)]
    else:
      self.squares = [chess.msg.Chesspiece() for _ in range(64)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      if len(self.squares) != 64:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (64, len(self.squares), 'self.squares')))
      for val1 in self.squares:
        _v1 = val1.player
        _x = _v1.id
        buff.write(_get_struct_B().pack(_x))
        _x = val1.kind
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.squares is None:
        self.squares = None
      end = 0
      self.squares = []
      for i in range(0, 64):
        val1 = chess.msg.Chesspiece()
        _v2 = val1.player
        start = end
        end += 1
        (_v2.id,) = _get_struct_B().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.kind = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.kind = str[start:end]
        self.squares.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      if len(self.squares) != 64:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (64, len(self.squares), 'self.squares')))
      for val1 in self.squares:
        _v3 = val1.player
        _x = _v3.id
        buff.write(_get_struct_B().pack(_x))
        _x = val1.kind
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.squares is None:
        self.squares = None
      end = 0
      self.squares = []
      for i in range(0, 64):
        val1 = chess.msg.Chesspiece()
        _v4 = val1.player
        start = end
        end += 1
        (_v4.id,) = _get_struct_B().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.kind = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.kind = str[start:end]
        self.squares.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
